# Generated by Django 4.1.1 on 2022-09-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('number_of_years', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('monthly_rate', models.FloatField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
